/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as AboutBrRouteImport } from './routes/about-br'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangProjectsRouteImport } from './routes/$lang/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBrRoute = AboutBrRouteImport.update({
  id: '/about-br',
  path: '/about-br',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangProjectsRoute = LangProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/about-br': typeof AboutBrRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-br': typeof AboutBrRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/about-br': typeof AboutBrRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$lang' | '/about-br' | '/$lang/projects' | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-br' | '/$lang/projects' | '/$lang'
  id: '__root__' | '/' | '/$lang' | '/about-br' | '/$lang/projects' | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  AboutBrRoute: typeof AboutBrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-br': {
      id: '/about-br'
      path: '/about-br'
      fullPath: '/about-br'
      preLoaderRoute: typeof AboutBrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/projects': {
      id: '/$lang/projects'
      path: '/projects'
      fullPath: '/$lang/projects'
      preLoaderRoute: typeof LangProjectsRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangProjectsRoute: typeof LangProjectsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangProjectsRoute: LangProjectsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  AboutBrRoute: AboutBrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
